export const apiURL = process.env.REACT_APP_API_URL ?? 'http://localhost:3001/v3';

export const apiPaths = {
    // places
    getPlaces: '/places',
    createPlace: '/places/create',
    getCompanyList: '/places/companyList',
    // routes
    getActiveRoute: '/tours/getActiveRoute',
    createNewRoute: '/tours/create',
    finishRoute: '/tours/finish',
    // users
    register: '/users/register',
    login: '/auth/login',
    get: '/auth/user',
    logout: '/auth/logout',
    markDepart: '/users/markDepart',
    userUpdate: '/users/userUpdate',
    // days
    createNewDay: '/days/create',
    finishDay: '/days/finish',
    getActiveDay: '/days/getActiveDay',
    getLastDay: '/days/getLastDay',
    getDays: '/days',
    getBurnedFuelByTour: '/days/burnedFuelByTour',
    // logs
    createNewLog: '/logs/create',
    createBorderCross: '/logs/createBorderCross',
    getLogs: '/logs',
    getLogById: '/logs/getById',
    attachTrailer: '/logs/attachTrailer',
    detachTrailer: '/logs/detachTrailer',
    loadingArrival: '/logs/loadingArrival',
    unloadingArrival: '/logs/unloadingArrival',
    // borders
    getBordersByCountry: '/borders/getByCountry',
    // vehicles
    getVehicleByRegistration: '/vehicles/findByRegistration',
    createVehicle: '/vehicles/create',
    getTrailersList: '/vehicles/trailers',
    getTrucksList: '/vehicles/trucks',
    editTrailer: '/vehicles/trailer/edit',
    editTruck: '/vehicles/truck/edit',
    // services
    createService: '/services/create',
    // loadings
    createLoad: '/loads/create',
    unloadingLoad: '/loads/unload',
    getNotUnloadedLoads: '/loads/getNotUnloadedLoads',
    getUnloadingPlace: '/loads/getUnloadingPlace',
    getLoadDetails: '/loads/getLoadDetails',
    // finances
    getPaymentMethods: '/payments',
    addPaymentMethod: '/payments/add',
    deletePaymentMethod: '/payments/delete',
    selectPaymentMethod: '/payments/select',
    createExpense: '/finances/create',
    getRefuelValueByTour: '/finances/getRefuelValueByTour',
}