type Countries = {
    [keyof: string]: string;
}


export const countries: Countries[] =
    [{ //en
        PL: 'Poland',
        DE: 'Germany',
        LT: 'Lithuania',
        AT: 'Austria',
        BA: 'Bosnia and Herzegovina',
        BE: 'Belgium',
        BG: 'Bulgaria',
        BY: 'Belarus',
        CA: 'Canada',
        CH: 'Switzerland',
        CN: 'China',
        CZ: 'Czech Republic',
        DK: 'Denmark',
        EE: 'Estonia',
        ES: 'Spain',
        FI: 'Finland',
        FR: 'France',
        GB: 'United Kingdom',
        GR: 'Greece',
        HR: 'Croatia',
        HU: 'Hungary',
        IT: 'Italy',
        KZ: 'Kazakhstan',
        LU: 'Luxembourg',
        LV: 'Latvia',
        NL: 'Netherlands',
        NO: 'Norway',
        PT: 'Portugal',
        RO: 'Romania',
        RU: 'Russian Federation',
        SE: 'Sweden',
        SK: 'Slovakia',
        SZ: 'Swaziland',
        TR: 'Turkey',
        UA: 'Ukraine',
    },
        {//pl
            PL: 'Polska',
            DE: 'Niemcy',
            LT: 'Litwa',
            AT: 'Austria',
            BA: 'Bośnia i Chercegowina',
            BE: 'Belgia',
            BG: 'Bułgaria',
            BY: 'Białoruś',
            CA: 'Kanada',
            CH: 'Szwajcaria',
            CN: 'Chiny',
            CZ: 'Czechy',
            DK: 'Dania',
            EE: 'Estonia',
            ES: 'Hiszpania',
            FI: 'Finlandia',
            FR: 'Francja',
            GB: 'Wielka Brytania (Anglia)',
            GR: 'Grecja',
            HR: 'Chorwacja',
            HU: 'Węgry',
            IT: 'Włochy',
            KZ: 'Kazachstan',
            LU: 'Luksemburg',
            LV: 'Łotwa',
            NL: 'Nederlandy (Holandia)',
            NO: 'Norwegia',
            PT: 'Portugalia',
            RO: 'Rumunia',
            RU: 'Rosja',
            SE: 'Szwecja',
            SK: 'Słowacja',
            SZ: 'Szwajcaria',
            TR: 'Turcja',
            UA: 'Ukraina',
        }];